"""empty message

Revision ID: cb561dd44d33
Revises: 44a2f1bf6e41
Create Date: 2019-01-31 17:49:23.742868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb561dd44d33'
down_revision = '44a2f1bf6e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historic_wall', sa.Column('img', sa.String(length=120), nullable=True))
    op.add_column('wall', sa.Column('img', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wall', 'img')
    op.drop_column('historic_wall', 'img')
    # ### end Alembic commands ###
